### PR TITLE
docs: advise the use of the "dev-dependency" label

### PR DESCRIPTION
**Pull request by wincent**

### CODE REVIEW

**Comment by thektan** [comment]
@wincent Non-contributors can't add labels. 😞

**Comment by jbalsas** [comment]
Hey @thektan, I'll try to figure out the necessary permissions for this throughout the week!

One thing I actually wanted to do, rather than this, was to create a proper `issue template` so enforcing this guidelines in regards to how to ask for things would become simpler. Maybe that would be a better approach?

**Comment by thektan** [comment]
@jbalsas Thanks!

+1 to issue templates! I think with issue templates you can include labels in them too.

**Comment by wincent** [comment]
Made mostly redundant by https://github.com/liferay/liferay-frontend-guidelines/pull/82 — closing.

**Pull request closed without merging**
