### PR TITLE
docs: add guidance on creating new NPM packages

### PR DESCRIPTION
**Pull request by wincent**
tl;dr: don't.

### CODE REVIEW

**Comment by jbalsas** [comment]
> tl;dr: don't.

Why don't you make this more obvious at the beginning of the article? 

I assume people will jump to `consider the costs` right away and look to simply confirm their bias that a new package is needed. So we might want to be a bit more specific about what should be the preferred option? 

...just saying...

**Comment by wincent** [comment]
@jbalsas: Is https://github.com/liferay/liferay-frontend-guidelines/pull/186/commits/95bdab176d35d6c34e7433099afe336399d61300 strong enough?

**Comment by jbalsas** [comment]
> @jbalsas: Is 95bdab1 strong enough?

That, might work...

ikillyou

**Comment by carloslancha** [comment]
> :warning: Creating a new package can be hazardous to your health, and to the health of your teammates. :skull_and_crossbones:

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2FNnGGHE0muVqpO%2Fgiphy.gif&token=applause" data-gitmeme-token="applause"></a>

**Comment by izaera** [comment]
:heart_eyes:

**Comment by wincent** [comment]
Ok, I consider that an approval.

**Pull request merged**
