### PR TITLE
docs: Clay CSS 3.x introduction

### PR DESCRIPTION
**Pull request by pat270**
Requested by @jbalsas, not sure what directory to place this in. I feel like this information is/will be duplicated in a lot of other documents (#213).

/cc @marcoscv-work @eduardoallegrini

### CODE REVIEW

**Comment by wincent** [comment]
> I feel like this information is/will be duplicated in a lot of other documents (#213).

I don't know how urgent @jbalsas considers this to be, but maybe we can pause one of these two PRs so that we can get one in first, and then make sure that the second one links out to the other one where appropriate instead of duplicating the same information in a different format.

**Comment by matuzalemsteles** [comment]
This is a type of documentation that would be great to be in the [Clay repository](https://github.com/liferay/clay/tree/master/docs) but we can just create a document that links to this one.

**Comment by pat270** [comment]
I don't mind pausing this one since #213 was first or adding something like this to the Clay repo. We can see how it plays out.

@matuzalemsteles I added a wiki https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions for @jonmak08 yesterday, would it be better in docs?

**Comment by matuzalemsteles** [comment]
> @matuzalemsteles I added a wiki https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions for @jonmak08 yesterday, would it be better in docs?

I see no problem with this being on the Wiki if it is the case of easy access for people but I have the impression that being in docs I seem easier to track.

**Comment by wincent** [comment]
> would it be better in docs?

The wiki is easier to update but less discoverable (because I think people are generally "trained" to seek the docs first), but you could link to your wiki article from the docs and have the best of both worlds.

**Comment by eduardoallegrini** [comment]
🤔 I took a look at the documentation and I think we can have both pages without duplicating the info. I'm trying to avoid repeating what you already wrote in this PR and leaving the space to link them once ready.

**Comment by pat270** [comment]
@eduardoallegrini I think it's ok to repeat. Personally, I like having all the info I need in one place rather than having to click around. I get easily lost.

**Comment by jonmak08** [comment]
Just adding my two cents... Doing what @wincent mentioned might seem to be the best way to have it versioned and updated, while also having the wiki information linked.  Does that approach not work?

**Comment by jbalsas** [comment]
I think we can simply merge this. We can always move it elsewhere or link it in the future.

My only doubt is wether `/css` is the folder for it... thoughts?

**Comment by pat270** [comment]
I can move this to the DXP folder. I don't really have an opinion on where it should live.

**Pull request merged**
