### PR TITLE
docs: add "environment" document

### PR DESCRIPTION
**Pull request by wincent**
Discusses "production" vs "development".

This is the provisional story for doing development. Will update to reflect any changes that happen in the course of this related ticket: https://issues.liferay.com/browse/LPS-95430

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
LGTM. I found this pretty helpful myself, a handful of those properties I never knew about or never knew why I used it. Great job!

**Comment by jbalsas** [comment]
Hey @wincent, this looks great to me! Do you want to add something in light of https://github.com/brianchandotcom/liferay-portal/pull/76953#issuecomment-521121103 and https://github.com/jbalsas/liferay-portal/pull/1870? Or do you prefer to merge this and then send a followup?

**Comment by wincent** [comment]
@jbalsas: I'll add another commit on top.

**Comment by wincent** [comment]
Ended up being a fairly big edit. I'll merge this and we can fix up any details that I might have gotten wrong or omitted.

**Comment by jbalsas** [comment]
Looks awesome! 👏

**Pull request merged**
