### PR TITLE
docs: add considerations before adding new dependencies

### PR DESCRIPTION
**Pull request by wincent**
File this one under "Rants".

### CODE REVIEW

**Comment by wincent** [comment]
Will merge this and address any feedback that comes along later.

**Comment by bryceosterhaus** [comment]
Glad you added this. The commands to check sizes were helpful in following along. 

As for lerna specifically, I was just looking into removing it last week. The one part I found hard to get rid of was the command `lerna version --conventional-commits`. I haven't looked too deep into this, but if we could do that without lerna, we would be fine with out lerna in clay.

**Comment by jbalsas** [comment]
bla bla bla

**Comment by jbalsas** [comment]
(sorry, couldn't resist it 😂)

**Pull request merged**
