### PR TITLE
bad: test the Semantic Pull Request bot

### PR DESCRIPTION
**Pull request by wincent**

### CODE REVIEW

**Comment by wincent** [comment]
Yay, correctly detects a bad commit and PR title:

BAD_COMMIT_WITHOUT_A_TYPE_by_wincent_·_Pull_Request__71_·_liferay_liferay-frontend-guidelines

**Comment by wincent** [comment]
I added a type, but a bad one, and it still complains, correctly.

**Comment by wincent** [comment]
With both commit and PR title fixed, it is green:

test__test_the_Semantic_Pull_Request_bot_by_wincent_·_Pull_Request__71_·_liferay_liferay-frontend-guidelines

**Comment by wincent** [comment]
And when I break the PR title, the bot complains again.

In other words, it's working! Closing this one.

**Comment by bryceosterhaus** [comment]
its working

**Pull request closed without merging**
