### PR TITLE
feat: add issue templates

### PR DESCRIPTION
**Pull request by wincent**
This can probably be improved but adding some "seed" versions to get the ball rolling.

~~Still TODO (future): figure out how to auto-label issues based on the template used.~~

Replaces: https://github.com/liferay/liferay-frontend-guidelines/pull/23

### CODE REVIEW

**Comment by wincent** [comment]
Sadly, can't test this until it is on master, but I modeled it on [the templates in the Prettier repo](https://github.com/prettier/prettier/tree/master/.github/ISSUE_TEMPLATE).

**Comment by wincent** [comment]
Hey @thektan, [over here](https://github.com/liferay/liferay-frontend-guidelines/pull/23#issuecomment-499593009) you said:

>  I think with issue templates you can include labels in them too.

Any idea how that works?

**Comment by wincent** [comment]
Aaand, found the answer [here](https://github.community/t5/How-to-use-Git-and-GitHub/Apply-labels-automatically-at-issue-creation/td-p/10719).

**Comment by jbalsas** [comment]
shutupandtakemymoney

**Comment by wincent** [comment]
It works:

New_Issue_·_liferay_liferay-frontend-guidelines

**Comment by thektan** [comment]
@wincent The issue templates look great! I actually saw the labels through their issue template manager in the repo settings. It's just a UI for the markdown doc, but just as another option:

Screenshot 2019-09-05 11 58 16

---

Screenshot 2019-09-05 11 59 38

**Comment by wincent** [comment]
@thektan: yeah, I knew about the UI although I can't see it on this repo due to privileges.

**Pull request merged**
